# Ejercicio 1
Crea un arreglo de 10 números aleatorios y luego modifica el arreglo con los valores desplazados, de tal forma que el mayor sea 1. Es decir, si el arreglo de números aleatorios tiene como valor máximo el 0.7, entonces debes sumarle a cada elemento 0.3. Luego imprime el arreglo en pantalla.


In [ ]:
import numpy as np

numeros = np.random.random([10]).round(1)
print(numeros)
maximo = np.max(numeros)
numeros = numeros + (1-maximo)
print(numeros)


[0.1 0.7 0.1 0.9 0.9 0.  0.4 0.5 0.8 0.6]
[0.2 0.8 0.2 1.  1.  0.1 0.5 0.6 0.9 0.7]


# Ejercicio 2

Crea un arreglo de 10 números aleatorios y modifica el arreglo de tal forma que el promedio esté en cero. Luego cuenta cuantos valores hay sobre cero y cuantos bajo cero, e imprime eso en pantalla.


In [ ]:
import numpy as np

numeros = np.random.random([10])*10
numeros = numeros.round(0)
print(numeros)
promedio = np.mean(numeros).round(1)
print(promedio)
numeros = numeros - promedio
print(numeros)
promedio = np.mean(numeros).round(1)
print(promedio)


print(f'Bajo cero {np.sum(numeros < 0)}')
print(f'Sobre cero {np.sum(numeros > 0)}')


[ 5.  9.  7.  4.  3. 10.  5.  6.  2.  3.]
5.4
[-0.4  3.6  1.6 -1.4 -2.4  4.6 -0.4  0.6 -3.4 -2.4]
-0.0
[-0.4 -1.4 -2.4 -0.4 -3.4 -2.4]
Bajo cero 6
Sobre cero 4


# Ejercicio 3
Crea un arreglo de 100 números aleatorios y suma solamente aquellos valores que sean mayores a 0.5.

In [ ]:
import numpy as np

numeros = (np.random.random([100])).round(1)
print(numeros)
print(f'La suma es {np.sum(numeros[numeros > 0.5])}')

[0.1 0.7 0.1 0.9 0.5 0.3 0.7 0.1 0.8 0.7 0.1 0.9 0.7 0.2 1.  0.9 0.3 0.6
 0.7 0.4 0.8 0.7 0.9 0.3 0.4 0.3 0.8 0.9 0.3 0.1 0.3 0.5 0.8 0.4 0.4 0.
 0.2 0.9 0.8 0.9 0.6 0.3 0.5 0.2 0.8 0.9 0.5 0.9 0.1 0.4 0.6 0.1 0.7 0.9
 0.6 0.4 0.6 0.2 0.6 0.6 0.5 0.4 0.7 0.3 0.4 0.2 0.8 0.9 1.  0.5 0.  0.2
 0.9 1.  0.5 0.1 0.7 0.5 0.2 0.7 0.2 0.2 0.2 0.4 0.8 0.2 0.9 0.5 0.7 0.5
 1.  0.1 0.3 0.7 0.3 0.4 0.2 0.9 0.6 0.9]
La suma es 37.1


# Ejercicio 4
Crea un arreglo de 100 números enteros aleatorios entre 1 y 10000 y encuentra el más cercano a 6543. Imprime el valor en pantalla.

In [ ]:
import numpy as np

value = 6543

# numeros = np.random.randint(1, 10000, [100])
numeros = (np.random.random([100])*10000).round(0)
print(numeros)
copia = np.abs(numeros - value)
print(copia)
i = np.argmin(copia)
print(f'El numero más cercano es {numeros[i]}')



[ 193. 4039. 5437. 4668. 6292.]
[6350. 2504. 1106. 1875.  251.]
El numero más cercano es 6292.0


# Ejercicio 5
Crea un arreglo de tamaño 100 con número aleatorios, retorna el valor máximo y luego reemplaza el valor en la posición del máximo en el arreglo por un cero.

In [ ]:
import numpy as np

numeros = (np.random.random([100])*100).round(0)
print(numeros)
print(f'El elementos más grande es {np.max(numeros)}')
numeros[np.argmax(numeros)] = 0
print(numeros)


[57. 98. 81. 49. 48. 72. 85. 27.  1. 96.]
El elementos más grande es 98.0
[57.  0. 81. 49. 48. 72. 85. 27.  1. 96.]


# Ejercicio 6
Escribe el código en Python que crea un arreglo 1D de 10 elementos con valores aleatorios enteros entre 0 y 9 y que despliegue el contenido del arreglo, así como el número de valles y crestas contenidos en el. Se definen como valles los números que son menores que sus dos vecinos inmediatos en el arreglo (a izquierda y derecha). Se definen como crestas los números que son mayores que sus dos vecinos inmediatos (a izquierda y derecha) en el arreglo. Por ejemplo:

In [ ]:
import numpy

numeros=(numpy.random.random([10])*9).round(1)
print(numeros)

#recorre arreglo y detecta valles y crestas
valles=0
crestas=0
for i in range(1,numeros.size-1):
    if(numeros[i]<numeros[i-1] and numeros[i]<numeros[i+1]):
        valles=valles+1
    if(numeros[i]>numeros[i-1] and numeros[i]>numeros[i+1]):
        crestas=crestas+1
print("Este arreglo tiene ",valles,"valles y ", crestas, "crestas")


[7.7 2.7 7.5 1.  8.  7.2 1.1 4.9 0.7 6.6]
Este arreglo tiene  4 valles y  3 crestas


# Ejercicio 7
Escribe el código Python que calcula el producto punto entre dos vectores a y b de largo 5. Los vectores se crean aleatoriamente. 
Por ejemplo:
[2  9  3  10 10]
[3  7  5  1  6]
El producto punto es igual a  154.0


In [ ]:
import numpy

#crea vectores y los despliega
a=(numpy.random.random([5])*10).round(0)
b=(numpy.random.random([5])*10).round(0)

print(a)
print(b)

#calcula producto punto
pdto_pto=0
for i in range(0, a.size):
    pdto_pto += a[i]*b[i]

print(f"El producto punto es igual a {pdto_pto}")

[0. 7. 2. 5. 4.]
[0. 8. 5. 4. 4.]
El producto punto es igual a 102.0


# Ejerccicio 8

Las agencias de pluviometría de las ciudades de Santiago y Mendoza sospechan que el cambio climático podría estar alterando el patrón de  precipitaciones de estas ciudades, haciéndolas más parecidas en términos de ocurrencias de lluvias. Para verificar esta sospecha ambas agencias registraron la existencia de lluvias para cada día del año 2017. 
Las agencias necesitan que construyas un programa en Python que despliegue por pantalla el número de días del año 2017 en que en ambas ciudades se presentó el mismo patrón de lluvias (es decir, en ambas llovió el mismo día o en ambas no llovió el mismo día). Para esto, el programa debe manejar dos arreglos unidimensionales (llamados Santiago y Mendoza) de 365 casillas cada uno. La casilla 0 representa el 1 de Enero, la casilla 1 el 2 de Enero y así sucesivamente. En cada casilla se almacena un 1 si hubo lluvias y 0 si no las hubo. 
Escribe un programa que despliegue por pantalla el número de días en que llovió en ambas ciudades simultáneamente y el número de días en que no llovió en ambas ciudades simultáneamente ciudades. Emula el contenido de los arreglos generando el contenido de manera aleatoria.


In [ ]:
import numpy

#crea arreglos Santiago y mendoza con registros (1: lluvia, 0: no lluvia)
Santiago=(numpy.random.random([365])).round(0)
Mendoza=(numpy.random.random([365])).round(0)

print(Santiago)
print(Mendoza)

#contador de dias en que llovio en ambas ciudades
lluvia=0

#contador de dias en que no llovio en ambas ciudades
no_lluvia=0

#recorre arreglos y cuenta los dias con igual patron
for i in range(0,Santiago.size):
  if(Santiago[i]==Mendoza[i] and Santiago[i]==0):
          no_lluvia=no_lluvia+1
  if(Santiago[i]==Mendoza[i] and Santiago[i]==1):
          lluvia=lluvia+1

print(f"LLovio en ambas ciudades: {lluvia} dias")
print(f"No lLovio en ambas ciudades: {no_lluvia} dias")


[1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1.
 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1.
 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1.
 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.
 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0.
 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.
 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1.
 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0.
 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0.
 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0.
 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.
 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1.

# Ejercicio 9

Escribe el código en Python que despliega en pantalla el número de veces que aparece cada número contenido en un arreglo 1D de 20 elementos enteros.  El arreglo se llena con números enteros aleatorios entre 0 y 5. Por ejemplo:

[2. 1. 2. 1. 3. 2. 2. 5. 3. 2. 3. 2. 3. 0. 1. 2. 3. 2. 3. 3.]


* Frecuencia del numero  2.0 :  8
* Frecuencia del numero  1.0 :  3
* Frecuencia del numero  3.0 :  7
* Frecuencia del numero  5.0 :  1
* Frecuencia del numero  0.0 :  1


In [ ]:
import numpy

#crea arreglo
a = (numpy.random.random([20])*5).round(0)
print(a)

#recorre arreglo, cada vez compara con el resto de los numeros
for i in range(0, a.size-1):
    iguales=0
    #verifica que el numero a[i] no haya sido revisado antes
    revisar= True
    for k in range(0,i):
        if(a[i]==a[k]):
                revisar= False
    #calcula frecuencia solo si el numero es "nuevo"
    if revisar :
        for j in range(i,a.size):
            if a[i]==a[j] and revisar==1:
                iguales=iguales+1
        print(f"Frecuencia del numero {a[i]}: ",iguales)


[2. 4. 4. 1. 3. 2. 3. 0. 5. 2. 2. 5. 4. 1. 2. 1. 3. 4. 2. 3.]
Frecuencia del numero 2.0:  6
Frecuencia del numero 4.0:  4
Frecuencia del numero 1.0:  3
Frecuencia del numero 3.0:  4
Frecuencia del numero 0.0:  1
Frecuencia del numero 5.0:  2


# Ejercicio 10
Cree una función llamada compara que retorne Verdadero si los elementos de dos arreglos pasados como parámetros son iguales, Falso de lo contrario. Un ejemplo de llamada es:

In [ ]:
import numpy as np

def compara(a, b):
  return np.all(a==b)

a = [1, 2, 3, 4]
b = [1, 2, 3, 4]
c = [1, 2, 3, 5]

print(compara(a, b)) # True
print(compara(a, c)) # False





True
False


# Ejercicio 11
El siguiente código se usa para clasificar a personas según su índice de masa corporal (IMC). 
```
import numpy as np

altura = [5.23, 7.17, 5.45, 5.98, 6.02]
peso = [135, 164, 137, 156, 161]

print(imc(altura, peso))

```
Implemente la función imc que recibe como parámetros una lista de alturas y otro de peso y retorna el índice de masa corporal para cada una de las personas. El imc se calcula como (peso en kilos)/(altura_en_metros^2).



In [ ]:
import numpy as np
 
def imc(altura, peso, sistema='metrico'):
  np_altura_m = np.array(altura)
  np_peso_kg = np.array(peso)

  indice = np_peso_kg / (np_altura_m ** 2)
  return indice

altura = [5.23, 7.17, 5.45, 5.98, 6.02]
peso = [135, 164, 137, 156, 161]
 
print(imc(altura, peso))



# Ejercicio 12

Al usar el código de la pregunta anterior, un nutricionista se dio cuenta que tenía datos tanto en el sistema métrico como en el imperial (como en el ejemplo). Dado eso, se les pide que agreguen un parámetro más a la función que diga que tipo de sistema de medición se usa, y si los datos están en el sistema imperial entonces los transforme a métrico. La altura se transforma multiplicando por 0.254 y el peso multiplicando por 0.453592. El código del ejemplo anterior quedaría de la siguiente forma:
```
import numpy as np

altura = [5.23, 7.17, 5.45, 5.98, 6.02]
peso = [135, 164, 137, 156, 161]

print(imc(altura, peso, 'imperial'))
```


In [ ]:
import numpy as np
 
def imc(altura, peso, sistema='metrico'):
  np_altura_m = np.array(altura)
  np_peso_kg = np.array(peso)
  if 'imperial' == sistema:
    np_altura_m = np_altura_m * 0.254
    np_peso_kg = np_peso_kg * 0.453592

  indice = np_peso_kg / (np_altura_m ** 2)

  return indice 

altura = [5.23, 7.17, 5.45, 5.98, 6.02]
peso = [135, 164, 137, 156, 161]

print(imc(altura, peso, 'imperial'))


# Ejercicio 13
Imaginese un arreglo de tamaño num y hay una mosca en la posición pos. La mosca se mueve en forma aleatoria (al azar) a la izquierda, a la derecha, o se queda quieta. En caso que la mosca se salga del arreglo, la mosca es atrapada por una araña. 
Para modelar el comportamiento de la mosca, ustede genera un número aleatorio entre 0 y 1, si el numero es menor a 0.33, entonces la mosca se mueve a la izquierda, en caso que sea un número entre 0.33 y 0.66, se mantiene quieta, y si es mayor a 0.66 se mueve a la derecha.
Cree una función que reciba num y pos e itere hasta que la mosca sea atrapada por alguna araña. Luego, muestre por pantalla el número de veces que la mosca estuvo en cada posición y el número total de movimientos realizados.
Sea I = Izquierda, D = derecha, y Q = quieto. Un ejemplo, para un arreglo de tamaño 5, con la mosca en posición inicial 2 y realizó los siguientes movimientos: D I I I D Q Q I  hubiera impreso por pantalla lo siguiente: 2 3 2 1 0
El número total de movimientos fue: 8

In [ ]:
import numpy
import random
def mosca(num,pos):    
  arreglo=numpy.zeros(num)    
  while pos>=0 and pos<len(arreglo):        
    arreglo[pos] += 1        
    temp=random.random()
    if temp<0.33:
      pos=pos-1
    elif temp>0.66:
      pos=pos+1
  print(arreglo)
  print("el numero de movimientos es ", arreglo.sum())
mosca(5,2)


[0. 0. 4. 6. 5.]
el numero de movimientos es  15.0
